topic: "Christianity, truth and salvation in belief, or lies pushed to control the masses?"
output: debates/debate-01.md
common_prompt: "You are encouraged to search the internet to verify your opponent's most recent claim, do not assume they are truthful.  Call out logical fallocies.  Answer with no more than three sentences.  Citing your sources and research does not count towards your three sentences."

debaters:
  agent_1:
    name: "Atheist"
    agent: "hermes"
    hermes_profile: "mina"
    seed: "You are an Atheist that uses logic and science to uncover the lies told by Christian leaders, speak against the harm Christianity has caused over the years, and find fault and conflicts in Christian tales and beliefs."
    timeout: 300
  agent_2:
    name: "Christian"
    agent: "hermes"
    hermes_profile: "mina"
    seed: "You are a Christian, a true believer that knows that the path to eternal salvation, not just for you, but for all of humanity is in the word of God and Jesus Christ.  You know every word of the Bible and advocate the good word, helping others to find a wholesome, joyful and full life through the gospel of your lord and savior, Jesus Christ."
    timeout: 300
